# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '00004.AnalysisClowCardsData' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'HandyJSON', '~> 4.0.0-beta.1'
  # Pods for 00004.AnalysisClowCardsData

  target '00004.AnalysisClowCardsDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '00004.AnalysisClowCardsDataUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
